name: Publish to GH Pages from master

on:
  push:
    branches:    
      - master    

jobs:
  build & deploy:
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2
    - name: Install Dependencies
      run: npm i
    - name: Build Vue.js app
      run: npm build
    - name: Build and Deploy
      uses: JamesIves/github-pages-deploy-action@releases/v3
      with:
        ACCESS_TOKEN: ${{ secrets.ACCESS_TOKEN }}
        BRANCH: gh-pages # The branch the action should deploy to.
        FOLDER: dist # The folder the action should deploy.
