name: Publish to GH Pages from master

on:
  push:
    branches:
      - master

env:
  CUSTOM_DOMAIN: perevedu.minii.ru

jobs:
  build_and_deploy:
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2
    - name: Install Dependencies
      run: npm i
    - name: Build Vue.js app
      run: npm run build
    - name: Deploy to GitHub Pages
      uses: crazy-max/ghaction-github-pages@v1.3.0
      with:
        target_branch: gh-pages
        build_dir: dist
        keep_history: true
        fqdn: ${{ env.CUSTOM_DOMAIN }}
      env:
        GITHUB_PAT: ${{ secrets.ACCESS_TOKEN }}
